#!/bin/bash
#
# Author: Tobias Schrader
set -o nounset

source engine.sh

debug=false
prg=$(basename "$0")

while getopts ':d' optname; do
  case $optname in
    d) debug=true;;
    :) echo "$prg: Argument for option $OPTARG is missing" >&2; exit 2;;
    \?) echo "$prg: Unknown option $OPTARG" >&2; exit 2;;
    *) echo "$prg: Internal error, unexpected option $OPTNAME" >&2; exit 3;;
  esac
done
shift $(( $OPTIND - 1 ))

# graphic representations
declare -A rep
rep[empty]=' '
rep[border]='#'
rep[falling]='@'
rep[base]='O'

declare -i tickrate=500000

declare -i score=0
declare -i lnum=0

#field
declare -i width=4
declare -i height=4

declare -i xsize=$width+2
declare -i ysize=$height+3

declare -a field

getfield() {
  local x=$1
  local y=$2
  echo "${field[$x + $width * $y]}"
}

setfield() {
  local x=$1
  local y=$2
  local val=$3
  field[$x + $width * $y]=$val
}



#piece
declare -i piece_x=$((width/2))
declare -i piece_y=0

forpiece() {
  
  $1 piece_x piece_y ${2:-''}
}

fall() {
  if connects piece; then
    land
  else
    move 0 1
  fi
}

slide() {
  local x=$1
  local newx=$((piece_x + x ))
  [[ $newx -ge 0 ]] && [[ $newx -lt $width ]] && move $x 0
}
turn() {
  :
}

move() {
    local x=$1
    local y=$2
    forpiece setfield empty
    ((piece_x+=$x))
    ((piece_y+=$y))
    forpiece setfield falling
  }

land() { #executed when piece lands
  forpiece setfield base
  score
  spawn
}

score() {
  local lnum=0
  [[ piece_y -eq 0 ]] && gameover;
  forpiece linecomplete
  ((score+=$lnum))
  lnum=0
}

gameover() {
  end
}

linecomplete() {
  local y=$2
  for (( x=0; x<$width; x++));do
    [[ $(getfield $x $y) == base ]] || return 1
  done
  downshift $y
  ((lnum++))
}

downshift() {
  local level=$1
  for ((y=$level;y>0;y--)); do
    for (( x=0; x<$width; x++));do
      setfield $x $y $(getfield $x $((y-1)) )
    done
  done
}

spawn() {
  piece_x=$((width/2))
  piece_y=0
  forpiece setfield falling
}
connects() { #todo: adjust for 4-block
  [[ $piece_y -ge $((height - 1 )) ]] && return 0
  [[ $(getfield $piece_x $((piece_y+1)) ) == 'base' ]] && return 0
  return 1
}

build_map() {
 for (( y=0; y < $height; y++ )); do
    for (( x=0; x < $width; x++ )); do
      map[$x+1 + ($y+1) * $xsize]=${rep[$(getfield $x $y)]}
    done
  done
  for ((i=0; i<${#score}; i++ )); do
    map[$i+1 *$xsize*($ysize-1)]=${score:$i:1}
  done
}

game_setup() {
  for (( y=0; y < $height; y++ )); do
    for (( x=0; x < $width; x++ )); do
      setfield $x $y empty
    done 
  done
  for ((x=0; x < $xsize; x++)); do
    map[$x]=${rep[border]}
    map[$x + $xsize * ($ysize -2)]=${rep[border]}
  done
  for ((y=0; y < $((ysize-1)); y++)); do
    map[$y*$xsize]=${rep[border]}
    map[$xsize - 1 + $xsize*$y]=${rep[border]}
  done

}

worldtick() {
  fall
  build_map
}

action() {
  local playerinput=$1
  case $playerinput in
    q) close ;;
    a) slide -1 ;;
    d) slide 1 ;;
    s) fall ;;
  esac
}

engine
