#!/bin/bash

set -o nounset

source engine.sh

debug=true

declare -i ysize=25
declare -i xsize=80
declare -i pos=xsize/2
declare -i gametick=0
declare -i min_width=7
declare -i current_width=xsize-2

declare -a left width

game_setup() {
  :
}

display() {
  clear_map
  for ((y=0;y<ysize;y++)) {
    for ((x=0;x<left[y];x++)) {
      map[y*xsize+x]='+'
    }
    for ((x=left[y];x<left[y]+width[y];x++)) {
      map[y*xsize+x]=' '
    }
    for ((x=left[y]+width[y];x<xsize;x++)) {
      map[y*xsize+x]='+'
    }
  }
  char='*'
  inbound=true
  local -i max=${left[ysize-1]}+${width[ysize-1]}
  if [[ $pos -lt ${left[ysize-1]} || $pos -ge $max ]]; then
    char='!'
    inbound=false
  fi
  map[(ysize-1)*xsize+pos]=$char
  draw
  $inbound || {
    tput cnorm
    stty echo
    tput cup $ysize 0
    exit 0
  }
}

action() {
  case $1 in
    j)
      ((pos--))
      ;;
    l)
      ((pos++))
      ;;
    q)
      close
      ;;
  esac
  display
}

worldtick() {
  for ((y=ysize-1;y>0;y--)) {
    left[y]=${left[y-1]}
    width[y]=${width[y-1]}
  }
  (( current_width>min_width && current_width--))
  width[0]=$current_width
  ((random=RANDOM%5))
  echo "random=$random ${left[0]} ${width[0]}" >&2
  ((random<2 && left[0]>1 && left[0]--))
  ((random>2 && xsize-width[0]-left[0] > 2 && left[0]++))
  echo "--------- ${left[0]} ${width[0]}" >&2
  display
  ((gametick++))
}

for ((y=0;y<ysize;y++)) {
  left[y]=1
  width[y]=$current_width
}

engine --autodraw
